"""empty message

Revision ID: 05770708e1f7
Revises: 94fbc4da5587
Create Date: 2019-08-24 15:21:21.475783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05770708e1f7'
down_revision = '94fbc4da5587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduler_jobs_timestamp', table_name='scheduler_jobs')
    op.drop_table('scheduler_jobs')
    op.add_column('job', sa.Column('cron', sa.String(length=50), nullable=True))
    op.add_column('job', sa.Column('is_start', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('triggers', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'triggers')
    op.drop_column('job', 'is_start')
    op.drop_column('job', 'cron')
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('triggers', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cron', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_jobs_timestamp', 'scheduler_jobs', ['timestamp'], unique=False)
    # ### end Alembic commands ###
