"""empty message

Revision ID: 183001055603
Revises: 
Create Date: 2019-08-16 23:51:49.112043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183001055603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('description', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variables', 'description')
    # ### end Alembic commands ###
