"""empty message

Revision ID: 1b4a51f3bb76
Revises: 
Create Date: 2019-08-17 22:08:33.023115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4a51f3bb76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_timestamp'), 'users', ['timestamp'], unique=False)
    op.create_table('case_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_group_timestamp'), 'case_group', ['timestamp'], unique=False)
    op.create_table('request_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_headers_timestamp'), 'request_headers', ['timestamp'], unique=False)
    op.create_table('test_case_start_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('time_strftime', sa.String(length=40), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_start_times_timestamp'), 'test_case_start_times', ['timestamp'], unique=False)
    op.create_table('variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=11), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('is_private', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_variables_timestamp'), 'variables', ['timestamp'], unique=False)
    op.create_table('testcase_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_model', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['case_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcase_scenes_timestamp'), 'testcase_scenes', ['timestamp'], unique=False)
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('regist_variable', sa.String(length=30), nullable=True),
    sa.Column('regular', sa.TEXT(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('request_headers_id', sa.Integer(), nullable=True),
    sa.Column('testcase_scene_id', sa.Integer(), nullable=True),
    sa.Column('hope_result', sa.String(length=200), nullable=True),
    sa.Column('is_model', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['case_group.id'], ),
    sa.ForeignKeyConstraint(['request_headers_id'], ['request_headers.id'], ),
    sa.ForeignKeyConstraint(['testcase_scene_id'], ['testcase_scenes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcases_timestamp'), 'testcases', ['timestamp'], unique=False)
    op.create_table('test_case_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('testcase_name', sa.String(length=50), nullable=False),
    sa.Column('testcase_url', sa.String(length=300), nullable=False),
    sa.Column('testcase_data', sa.TEXT(), nullable=True),
    sa.Column('testcase_method', sa.String(length=10), nullable=False),
    sa.Column('testcase_hope_result', sa.String(length=200), nullable=True),
    sa.Column('response_body', sa.TEXT(), nullable=True),
    sa.Column('testcase_test_result', sa.String(length=10), nullable=True),
    sa.Column('testcase_id', sa.Integer(), nullable=True),
    sa.Column('testcase_start_time_id', sa.Integer(), nullable=True),
    sa.Column('old_sql_value', sa.TEXT(), nullable=True),
    sa.Column('new_sql_value', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ),
    sa.ForeignKeyConstraint(['testcase_start_time_id'], ['test_case_start_times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_case_result_timestamp'), 'test_case_result', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_result_timestamp'), table_name='test_case_result')
    op.drop_table('test_case_result')
    op.drop_index(op.f('ix_testcases_timestamp'), table_name='testcases')
    op.drop_table('testcases')
    op.drop_index(op.f('ix_testcase_scenes_timestamp'), table_name='testcase_scenes')
    op.drop_table('testcase_scenes')
    op.drop_index(op.f('ix_variables_timestamp'), table_name='variables')
    op.drop_table('variables')
    op.drop_index(op.f('ix_test_case_start_times_timestamp'), table_name='test_case_start_times')
    op.drop_table('test_case_start_times')
    op.drop_index(op.f('ix_request_headers_timestamp'), table_name='request_headers')
    op.drop_table('request_headers')
    op.drop_index(op.f('ix_case_group_timestamp'), table_name='case_group')
    op.drop_table('case_group')
    op.drop_index(op.f('ix_users_timestamp'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
