"""empty message

Revision ID: 268f93db0919
Revises: 05770708e1f7
Create Date: 2019-08-25 13:19:07.852324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268f93db0919'
down_revision = '05770708e1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('mail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'mail', ['mail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'mail_id')
    # ### end Alembic commands ###
