"""empty message

Revision ID: 94b761cbffbc
Revises: 183001055603
Create Date: 2019-08-17 13:45:14.999330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b761cbffbc'
down_revision = '183001055603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase_scenes', sa.Column('is_model', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcase_scenes', 'is_model')
    # ### end Alembic commands ###
