"""empty message

Revision ID: 94fbc4da5587
Revises: 242bb9c9830a
Create Date: 2019-08-22 22:20:33.761299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fbc4da5587'
down_revision = '242bb9c9830a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('triggers', sa.String(length=50), nullable=True),
    sa.Column('cron', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_jobs_timestamp'), 'scheduler_jobs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_jobs_timestamp'), table_name='scheduler_jobs')
    op.drop_table('scheduler_jobs')
    # ### end Alembic commands ###
